// P5W first batch 50 product seed - 自动生成
// 跑: npx tsx prisma/seed_first50.ts
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const products = [
  {
    "name": "DCA_Gold_Grid",
    "description": "【典藏级】 DCA_Gold_Grid 是一款专为黄金 (XAUUSD) 行情设计的网格型EA。\n\n核心算法: 基于 GRID 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖网格 等多种行情。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/DCA_Gold_Grid.mq5",
    "ex5Url": "/downloads/products/DCA_Gold_Grid.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 网格 · GOLD",
    "productHighlights": "• 网格 策略\n• 适配品种: GOLD, 黄金\n• GRID 等多种技术指标",
    "algorithmicCore": "核心算法采用 GRID 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 网格 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "网格",
    "capabilityTags": "[\"GRID\", \"GOLD\", \"黄金\", \"网格\", \"典藏级\", \"王牌\"]",
    "isActive": true,
    "isFeatured": true,
    "publishedAt": "2026-08-14T12:43:20.402661"
  },
  {
    "name": "GoldArbitrageXpert",
    "description": "【典藏级】 GoldArbitrageXpert 是一款专为黄金 (XAUUSD) 行情设计的对冲套利型EA。\n\n核心算法: 基于 ARBITRAGE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖对冲套利 等多种行情。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/GoldArbitrageXpert.mq5",
    "ex5Url": "/downloads/products/GoldArbitrageXpert.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 对冲套利 · GOLD",
    "productHighlights": "• 对冲套利 策略\n• 适配品种: GOLD, 黄金\n• ARBITRAGE 等多种技术指标",
    "algorithmicCore": "核心算法采用 ARBITRAGE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 对冲套利 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "对冲套利",
    "capabilityTags": "[\"ARBITRAGE\", \"GOLD\", \"黄金\", \"对冲套利\", \"典藏级\", \"王牌\"]",
    "isActive": true,
    "isFeatured": true,
    "publishedAt": "2026-08-14T12:43:20.402729"
  },
  {
    "name": "GoldArbitrageXpertv1",
    "description": "【典藏级】 GoldArbitrageXpertv1 是一款专为黄金 (XAUUSD) 行情设计的对冲套利型EA。\n\n核心算法: 基于 ARBITRAGE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖对冲套利 等多种行情。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/GoldArbitrageXpertv1.mq5",
    "ex5Url": "/downloads/products/GoldArbitrageXpertv1.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 对冲套利 · GOLD",
    "productHighlights": "• 对冲套利 策略\n• 适配品种: GOLD, 黄金\n• ARBITRAGE 等多种技术指标",
    "algorithmicCore": "核心算法采用 ARBITRAGE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 对冲套利 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "对冲套利",
    "capabilityTags": "[\"ARBITRAGE\", \"GOLD\", \"黄金\", \"对冲套利\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402763"
  },
  {
    "name": "GoldArbitrageXpertv2.1",
    "description": "【典藏级】 GoldArbitrageXpertv2.1 是一款专为黄金 (XAUUSD) 行情设计的对冲套利型EA。\n\n核心算法: 基于 ARBITRAGE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖对冲套利 等多种行情。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/GoldArbitrageXpertv2.1.mq5",
    "ex5Url": "/downloads/products/GoldArbitrageXpertv2.1.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 对冲套利 · GOLD",
    "productHighlights": "• 对冲套利 策略\n• 适配品种: GOLD, 黄金\n• ARBITRAGE 等多种技术指标",
    "algorithmicCore": "核心算法采用 ARBITRAGE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 对冲套利 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "对冲套利",
    "capabilityTags": "[\"ARBITRAGE\", \"GOLD\", \"黄金\", \"对冲套利\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402786"
  },
  {
    "name": "GoldArbitrageXpertv2.2",
    "description": "【典藏级】 GoldArbitrageXpertv2.2 是一款专为黄金 (XAUUSD) 行情设计的对冲套利型EA。\n\n核心算法: 基于 ARBITRAGE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖对冲套利 等多种行情。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/GoldArbitrageXpertv2.2.mq5",
    "ex5Url": "/downloads/products/GoldArbitrageXpertv2.2.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 对冲套利 · GOLD",
    "productHighlights": "• 对冲套利 策略\n• 适配品种: GOLD, 黄金\n• ARBITRAGE 等多种技术指标",
    "algorithmicCore": "核心算法采用 ARBITRAGE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 对冲套利 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "对冲套利",
    "capabilityTags": "[\"ARBITRAGE\", \"GOLD\", \"黄金\", \"对冲套利\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402803"
  },
  {
    "name": "MAM_Crossover_Trader",
    "description": "【专业级】 MAM_Crossover_Trader 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS, TRADE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/MAM_Crossover_Trader.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/MAM_Crossover_Trader.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS/TRADE 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS, TRADE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"TRADE\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402824"
  },
  {
    "name": "PZ_ReversalTrendFollowingEA",
    "description": "【专业级】 PZ_ReversalTrendFollowingEA 是一款趋势跟踪型EA。\n\n核心算法: 基于 REVERSAL, TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 反转, 均值回归 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/PZ_ReversalTrendFollowingEA.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/PZ_ReversalTrendFollowingEA.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/反转/均值回归 策略\n• 适配品种: 多品种\n• REVERSAL/TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 REVERSAL, TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/反转/均值回归 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"REVERSAL\", \"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402857"
  },
  {
    "name": "_hpcs_fastslowmacrosssover_mt4_ea_v01_we",
    "description": "【专业级】 _hpcs_fastslowmacrosssover_mt4_ea_v01_we 是一款对冲套利型EA。\n\n核心算法: 基于 CROSS, WMA 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 剥头皮, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/_hpcs_fastslowmacrosssover_mt4_ea_v01_we.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/_hpcs_fastslowmacrosssover_mt4_ea_v01_we.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/剥头皮/对冲套利 策略\n• 适配品种: 多品种\n• CROSS/WMA 等多种技术指标",
    "algorithmicCore": "核心算法采用 CROSS, WMA 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/剥头皮/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"CROSS\", \"WMA\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402875"
  },
  {
    "name": "3MaCross_EA",
    "description": "【专业级】 3MaCross_EA 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/3MaCross_EA.mq5",
    "ex5Url": "/downloads/products/3MaCross_EA.ex5",
    "ex4Url": "/downloads/products/3MaCross_EA.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402891"
  },
  {
    "name": "CrossMA",
    "description": "【专业级】 CrossMA 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/CrossMA.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/CrossMA.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402905"
  },
  {
    "name": "EMA_CROSS_2",
    "description": "【专业级】 EMA_CROSS_2 是一款对冲套利型EA。\n\n核心算法: 基于 EMA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/EMA_CROSS_2.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/EMA_CROSS_2.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• EMA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 EMA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"EMA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402920"
  },
  {
    "name": "MACDcrossAUDD1",
    "description": "【专业级】 MACDcrossAUDD1 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/MACDcrossAUDD1.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/MACDcrossAUDD1.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402935"
  },
  {
    "name": "Universalmacrossea_www_forex-instruments_info",
    "description": "【专业级】 Universalmacrossea_www_forex-instruments_info 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/Universalmacrossea_www_forex-instruments_info.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/Universalmacrossea_www_forex-instruments_info.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402949"
  },
  {
    "name": "close_cross_ma",
    "description": "【专业级】 close_cross_ma 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/close_cross_ma.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/close_cross_ma.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402965"
  },
  {
    "name": "ma_price_cross",
    "description": "【专业级】 ma_price_cross 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/ma_price_cross.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/ma_price_cross.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402979"
  },
  {
    "name": "macross",
    "description": "【专业级】 macross 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/macross.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/macross.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.402994"
  },
  {
    "name": "ttn-201712-market_weather_dual_ma_cross",
    "description": "【专业级】 ttn-201712-market_weather_dual_ma_cross 是一款对冲套利型EA。\n\n核心算法: 基于 MA, CROSS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势, 对冲套利 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/ttn-201712-market_weather_dual_ma_cross.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/ttn-201712-market_weather_dual_ma_cross.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势/对冲套利 策略\n• 适配品种: 多品种\n• MA/CROSS 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, CROSS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势/对冲套利 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"CROSS\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403008"
  },
  {
    "name": "EA-MQL4_Experts_MATrend",
    "description": "【专业级】 EA-MQL4_Experts_MATrend 是一款趋势跟踪型EA。\n\n核心算法: 基于 MA, TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/EA-MQL4_Experts_MATrend.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/EA-MQL4_Experts_MATrend.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• MA/TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403023"
  },
  {
    "name": "EA-MQL4_Experts_TrendMacd",
    "description": "【专业级】 EA-MQL4_Experts_TrendMacd 是一款趋势跟踪型EA。\n\n核心算法: 基于 MA, TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/EA-MQL4_Experts_TrendMacd.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/EA-MQL4_Experts_TrendMacd.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• MA/TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403037"
  },
  {
    "name": "TrendMacd",
    "description": "【专业级】 TrendMacd 是一款趋势跟踪型EA。\n\n核心算法: 基于 MA, TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/TrendMacd.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/TrendMacd.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• MA/TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403053"
  },
  {
    "name": "TrendMap",
    "description": "【专业级】 TrendMap 是一款趋势跟踪型EA。\n\n核心算法: 基于 MA, TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/TrendMap.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/TrendMap.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• MA/TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403066"
  },
  {
    "name": "Yumerain_Experts_MATrend",
    "description": "【专业级】 Yumerain_Experts_MATrend 是一款趋势跟踪型EA。\n\n核心算法: 基于 MA, TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/Yumerain_Experts_MATrend.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/Yumerain_Experts_MATrend.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• MA/TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"MA\", \"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403080"
  },
  {
    "name": "TrendFollowerRainbowMethodkyast773",
    "description": "【专业级】 TrendFollowerRainbowMethodkyast773 是一款趋势跟踪型EA。\n\n核心算法: 基于 TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/TrendFollowerRainbowMethodkyast773.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/TrendFollowerRainbowMethodkyast773.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势 · ETH",
    "productHighlights": "• 趋势 策略\n• 适配品种: ETH\n• TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"TREND\", \"ETH\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403095"
  },
  {
    "name": "TrendMeLeaveMe",
    "description": "【专业级】 TrendMeLeaveMe 是一款趋势跟踪型EA。\n\n核心算法: 基于 TREND 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/TrendMeLeaveMe.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/TrendMeLeaveMe.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403110"
  },
  {
    "name": "simple_news_filter_for_xauusd_trading_on_mt5",
    "description": "【标准级】 simple_news_filter_for_xauusd_trading_on_mt5 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 FILTER, SAR, NEWS 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/simple_news_filter_for_xauusd_trading_on_mt5.mq5",
    "ex5Url": "/downloads/products/simple_news_filter_for_xauusd_trading_on_mt5.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 3 (Basic)",
    "score": 9,
    "positioning": "标准级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• FILTER/SAR/NEWS 等多种技术指标",
    "algorithmicCore": "核心算法采用 FILTER, SAR, NEWS 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"FILTER\", \"SAR\", \"NEWS\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403128"
  },
  {
    "name": "SimpleRSIBollingerBandEntry",
    "description": "【标准级】 SimpleRSIBollingerBandEntry 是一款EA。\n\n核心算法: 基于 BOLLINGER, RSI, TRADE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/SimpleRSIBollingerBandEntry.mq5",
    "ex5Url": "/downloads/products/SimpleRSIBollingerBandEntry.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 3 (Basic)",
    "score": 9,
    "positioning": "标准级 · 通用",
    "productHighlights": "• 通用 策略\n• 适配品种: 多品种\n• BOLLINGER/RSI/TRADE 等多种技术指标",
    "algorithmicCore": "核心算法采用 BOLLINGER, RSI, TRADE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"BOLLINGER\", \"RSI\", \"TRADE\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403144"
  },
  {
    "name": "AMA",
    "description": "【专业级】 AMA 是一款指标。\n\n核心算法: 基于 MA 等技术指标,实现精准的行情分析。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "INDICATOR",
    "fileUrl": "/downloads/products/AMA.mq5",
    "ex5Url": "/downloads/products/AMA.ex5",
    "ex4Url": "/downloads/products/AMA.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用",
    "productHighlights": "• 通用 策略\n• 适配品种: 多品种\n• MA 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403162"
  },
  {
    "name": "ATR",
    "description": "【专业级】 ATR 是一款指标。\n\n核心算法: 基于 ATR 等技术指标,实现精准的行情分析。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "INDICATOR",
    "fileUrl": "/downloads/products/ATR.mq5",
    "ex5Url": "/downloads/products/ATR.ex5",
    "ex4Url": "/downloads/products/ATR.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用",
    "productHighlights": "• 通用 策略\n• 适配品种: 多品种\n• ATR 等多种技术指标",
    "algorithmicCore": "核心算法采用 ATR 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"ATR\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403178"
  },
  {
    "name": "EA-MQL4_Indicators_EasyTrend",
    "description": "【专业级】 EA-MQL4_Indicators_EasyTrend 是一款趋势跟踪型指标。\n\n核心算法: 基于 TREND 等技术指标,实现精准的行情分析。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "INDICATOR",
    "fileUrl": "/downloads/products/EA-MQL4_Indicators_EasyTrend.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/EA-MQL4_Indicators_EasyTrend.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403192"
  },
  {
    "name": "EA-MQL4_Indicators_Trend-V20",
    "description": "【专业级】 EA-MQL4_Indicators_Trend-V20 是一款趋势跟踪型指标。\n\n核心算法: 基于 TREND 等技术指标,实现精准的行情分析。\n\n适用场景: 覆盖趋势 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "INDICATOR",
    "fileUrl": "/downloads/products/EA-MQL4_Indicators_Trend-V20.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/EA-MQL4_Indicators_Trend-V20.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 趋势",
    "productHighlights": "• 趋势 策略\n• 适配品种: 多品种\n• TREND 等多种技术指标",
    "algorithmicCore": "核心算法采用 TREND 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 趋势 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "趋势",
    "capabilityTags": "[\"TREND\", \"趋势\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403205"
  },
  {
    "name": "VisualTrader-BUYScript",
    "description": "【专业级】 VisualTrader-BUYScript 是一款工具。\n\n核心算法: 基于 TRADE 等技术指标,实现精准的行情分析。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "SCRIPT",
    "fileUrl": "/downloads/products/VisualTrader-BUYScript.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/VisualTrader-BUYScript.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用",
    "productHighlights": "• 通用 策略\n• 适配品种: 多品种\n• TRADE 等多种技术指标",
    "algorithmicCore": "核心算法采用 TRADE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"TRADE\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403220"
  },
  {
    "name": "RiskLibrary",
    "description": "【专业级】 RiskLibrary 是一款工具。\n\n核心算法: 基于 RISK, ATR 等技术指标,实现精准的行情分析。\n\n适用场景: 适用于风控管理场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "LIBRARY",
    "fileUrl": "/downloads/products/RiskLibrary.mq5",
    "ex5Url": "/downloads/products/RiskLibrary.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 风控管理",
    "productHighlights": "• 风控管理 策略\n• 适配品种: 多品种\n• RISK/ATR 等多种技术指标",
    "algorithmicCore": "核心算法采用 RISK, ATR 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 风控管理 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "风控管理",
    "capabilityTags": "[\"RISK\", \"ATR\", \"风控管理\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403236"
  },
  {
    "name": "GoldArbitrageXpertv2.3",
    "description": "【典藏级】 GoldArbitrageXpertv2.3 是一款专为黄金 (XAUUSD) 行情设计的对冲套利型EA。\n\n核心算法: 基于 ARBITRAGE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖对冲套利 等多种行情。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/GoldArbitrageXpertv2.3.mq5",
    "ex5Url": "/downloads/products/GoldArbitrageXpertv2.3.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 对冲套利 · GOLD",
    "productHighlights": "• 对冲套利 策略\n• 适配品种: GOLD, 黄金\n• ARBITRAGE 等多种技术指标",
    "algorithmicCore": "核心算法采用 ARBITRAGE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 对冲套利 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "对冲套利",
    "capabilityTags": "[\"ARBITRAGE\", \"GOLD\", \"黄金\", \"对冲套利\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403253"
  },
  {
    "name": "GoldTraderEA",
    "description": "【典藏级】 GoldTraderEA 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 TRADE 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/GoldTraderEA.mq5",
    "ex5Url": "/downloads/products/GoldTraderEA.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n• TRADE 等多种技术指标",
    "algorithmicCore": "核心算法采用 TRADE 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"TRADE\", \"GOLD\", \"黄金\", \"通用\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403270"
  },
  {
    "name": "SignalPollerEA_Gold_v1.0",
    "description": "【典藏级】 SignalPollerEA_Gold_v1.0 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 综合多因子模型,稳健风控。\n\n适用场景: 适用于信号提示场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/SignalPollerEA_Gold_v1.0.mq5",
    "ex5Url": "/downloads/products/SignalPollerEA_Gold_v1.0.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 信号提示 · GOLD",
    "productHighlights": "• 信号提示 策略\n• 适配品种: GOLD, 黄金\n•  等多种技术指标",
    "algorithmicCore": "核心算法采用  策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 信号提示 行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "信号提示",
    "capabilityTags": "[\"GOLD\", \"黄金\", \"信号提示\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403284"
  },
  {
    "name": "gold",
    "description": "【典藏级】 gold 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 综合多因子模型,稳健风控。\n\n适用场景: 适用于通用场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/gold.mq5",
    "ex5Url": "/downloads/products/gold.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n•  等多种技术指标",
    "algorithmicCore": "核心算法采用  策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"GOLD\", \"黄金\", \"通用\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403298"
  },
  {
    "name": "ka-gold_bot",
    "description": "【典藏级】 ka-gold_bot 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 综合多因子模型,稳健风控。\n\n适用场景: 适用于通用场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/ka-gold_bot.mq5",
    "ex5Url": "/downloads/products/ka-gold_bot.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n•  等多种技术指标",
    "algorithmicCore": "核心算法采用  策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"GOLD\", \"黄金\", \"通用\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403315"
  },
  {
    "name": "ka-gold_bot_49811b3d",
    "description": "【典藏级】 ka-gold_bot_49811b3d 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 综合多因子模型,稳健风控。\n\n适用场景: 适用于通用场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/ka-gold_bot_49811b3d.mq5",
    "ex5Url": "/downloads/products/ka-gold_bot_49811b3d.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n•  等多种技术指标",
    "algorithmicCore": "核心算法采用  策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"GOLD\", \"黄金\", \"通用\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403328"
  },
  {
    "name": "shen-gold",
    "description": "【典藏级】 shen-gold 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 综合多因子模型,稳健风控。\n\n适用场景: 适用于通用场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/shen-gold.mq5",
    "ex5Url": "/downloads/products/shen-gold.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n•  等多种技术指标",
    "algorithmicCore": "核心算法采用  策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"GOLD\", \"黄金\", \"通用\", \"典藏级\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403342"
  },
  {
    "name": "ATRStopLoss_Ind",
    "description": "【专业级】 ATRStopLoss_Ind 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 STOPLOSS, ATR 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/ATRStopLoss_Ind.mq5",
    "ex5Url": "/downloads/products/ATRStopLoss_Ind.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n• STOPLOSS/ATR 等多种技术指标",
    "algorithmicCore": "核心算法采用 STOPLOSS, ATR 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"STOPLOSS\", \"ATR\", \"GOLD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403358"
  },
  {
    "name": "EA_Dashboard",
    "description": "【专业级】 EA_Dashboard 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/EA_Dashboard.mq5",
    "ex5Url": "/downloads/products/EA_Dashboard.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403373"
  },
  {
    "name": "EA_ULTRA_AGGRESSIVE",
    "description": "【专业级】 EA_ULTRA_AGGRESSIVE 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/EA_ULTRA_AGGRESSIVE.mq5",
    "ex5Url": "/downloads/products/EA_ULTRA_AGGRESSIVE.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403390"
  },
  {
    "name": "Footprint_CVD",
    "description": "【专业级】 Footprint_CVD 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/Footprint_CVD.mq5",
    "ex5Url": "/downloads/products/Footprint_CVD.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403406"
  },
  {
    "name": "Goldwarrior02b",
    "description": "【典藏级】 Goldwarrior02b 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 综合多因子模型,稳健风控。\n\n适用场景: 适用于通用场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/Goldwarrior02b.mq5",
    "ex5Url": null,
    "ex4Url": "/downloads/products/Goldwarrior02b.ex4",
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 1 (Premium/VIP)",
    "score": 18,
    "positioning": "典藏级 · 通用 · GOLD",
    "productHighlights": "• 通用 策略\n• 适配品种: GOLD, 黄金\n•  等多种技术指标",
    "algorithmicCore": "核心算法采用  策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,可对接机构级资金管理",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"GOLD\", \"黄金\", \"通用\", \"典藏级\", \"王牌\"]",
    "isActive": true,
    "isFeatured": true,
    "publishedAt": "2026-08-14T12:43:20.403420"
  },
  {
    "name": "Footprint_Delta",
    "description": "【专业级】 Footprint_Delta 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/Footprint_Delta.mq5",
    "ex5Url": "/downloads/products/Footprint_Delta.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403447"
  },
  {
    "name": "Footprint_POC",
    "description": "【专业级】 Footprint_POC 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/Footprint_POC.mq5",
    "ex5Url": "/downloads/products/Footprint_POC.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403462"
  },
  {
    "name": "ParityExporter",
    "description": "【专业级】 ParityExporter 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/ParityExporter.mq5",
    "ex5Url": "/downloads/products/ParityExporter.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403477"
  },
  {
    "name": "QuantumMathAI_V6_Guardian",
    "description": "【专业级】 QuantumMathAI_V6_Guardian 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于风控管理场景。\n\n风控: 内置仓位管理、止损止盈,可对接多账户风控体系。",
    "category": "EA",
    "fileUrl": "/downloads/products/QuantumMathAI_V6_Guardian.mq5",
    "ex5Url": "/downloads/products/QuantumMathAI_V6_Guardian.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 风控管理 · XAUUSD",
    "productHighlights": "• 风控管理 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 风控管理 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "风控管理",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"风控管理\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403492"
  },
  {
    "name": "SMC_Visual",
    "description": "【专业级】 SMC_Visual 是一款专为黄金 (XAUUSD) 行情设计的EA。\n\n核心算法: 基于 MA, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 适用于通用场景。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/SMC_Visual.mq5",
    "ex5Url": "/downloads/products/SMC_Visual.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 通用 · XAUUSD",
    "productHighlights": "• 通用 策略\n• 适配品种: XAUUSD, 黄金\n• MA/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 MA, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于  行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "通用",
    "capabilityTags": "[\"MA\", \"SCALP\", \"XAUUSD\", \"黄金\", \"通用\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403508"
  },
  {
    "name": "StochasticScalper",
    "description": "【专业级】 StochasticScalper 是一款专为黄金 (XAUUSD) 行情设计的高频剥头皮型EA。\n\n核心算法: 基于 STOCH, SCALP 等技术指标,实现自动化的交易信号生成。\n\n适用场景: 覆盖剥头皮 等多种行情。\n\n风控: 基础止损止盈,建议配合资金管理模块。",
    "category": "EA",
    "fileUrl": "/downloads/products/StochasticScalper.mq5",
    "ex5Url": "/downloads/products/StochasticScalper.ex5",
    "ex4Url": null,
    "version": "1.0",
    "requiredPlan": "WEEKLY",
    "isFree": false,
    "tier": "Tier 2 (Pro)",
    "score": 13,
    "positioning": "专业级 · 剥头皮 · XAUUSD",
    "productHighlights": "• 剥头皮 策略\n• 适配品种: XAUUSD, 黄金\n• STOCH/SCALP 等多种技术指标",
    "algorithmicCore": "核心算法采用 STOCH, SCALP 策略组合,内置多层过滤与风控机制,确保信号质量与执行稳定性。",
    "practicalApplication": "适用于 剥头皮 行情,适合中小资金账户",
    "riskControl": "内置止损止盈、仓位管理、最大回撤控制,支持多账户风控对接。",
    "subcategory": "剥头皮",
    "capabilityTags": "[\"STOCH\", \"SCALP\", \"XAUUSD\", \"黄金\", \"剥头皮\"]",
    "isActive": true,
    "isFeatured": false,
    "publishedAt": "2026-08-14T12:43:20.403525"
  }
];

async function main() {
  console.log(`Seeding ${products.length} products...`);
  for (const p of products) {
    await prisma.product.upsert({
      where: { name: p.name },
      create: p,
      update: p,
    });
  }
  console.log(`Done: ${products.length} products upserted.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
